### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by Jorges1000** [bhuvad/SpaNorm#2]
Hi,

When trying to install SpaNorm I get the error "requires R>=4.4". I am on R 4.3.1 on ubuntu system. Does it really require R 4.4 or is it related to the "R-CMD-check Failing" warning in the README?

**Comment by bhuvad** [comment]
Hi Jorge,

SpaNorm does not require 4.4 but because of a planned submission to Bioconductor, we have to enforce the latest version of R. The easiest approach is to upgrade R but that will mean that you need to upgrade all other packages and I know that can be a pain at times. We have tested SpaNorm and it should work with lower versions of R (including >=4.3.0). My advice would be that you download the source code locally, modify the version dependency, and install the package. Detailed instructions follow (for you or other users wanting to do the same):

1. Using command line, navigate to the directory where you want to install the package
1. Download the source code using `git clone https://github.com/bhuvad/SpaNorm.git`
1. Modify the R dependency in the line below to R (>= 4.3) https://github.com/bhuvad/SpaNorm/blob/de33b2d5357fa0bda20022c2dc9344cbde009734/DESCRIPTION#L24
1. Install the package using `install.packages("path_to_SpaNorm_dir", repos = NULL, type = "source")` 

Though this option allows you to work with SpaNorm with a lower version of R, you would have to repeat it each time updates are made to the package so if you do not have any specific reasons for using a lower R version, I would advise you to upgrade your R.

Hope this helps.

Cheers,
Dharmesh
